var $ = window.$ = window.jQuery = require('jquery')
require('svg4everybody')({polyfill: true})
window.Tether = require('tether')
require('bootstrap')
if ($('body.page-contact')) require('./contact/contact')
if ($('body.page-inspiration')) require('./inspiration/inspiration')
